// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.cloudnative.grpc;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string price = 3;</code>
   */
  java.lang.String getPrice();
  /**
   * <code>string price = 3;</code>
   */
  com.google.protobuf.ByteString
      getPriceBytes();
}
