// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.cloudnative.grpc;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
